server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FitBuddy?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete
knife4j:
  enable: true
  openapi:
    title: FitBuddyInterfaceDocumentation
    email: 3146731710@qq.com
    version: v1.0
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: test
        api-rule: package
        api-rule-resources:
          - com.yijinchan